### ISSUE TITLE
Put Settings Window on Top when Opening it 

### ISSUE THREAD

**Issue by thelooter** [trigg/Discover#207] opened 2022-03-13 11:54 UTC
Currently when you open the Settings Window it's not on top. Make it appear above all the other windows.
System: Manjaro Linux

**Comment by midget3111** [comment] 2022-03-13 11:57
So, this should be fixed on the latest stable I think. It should open a landing page on initial boot which the settings can be accessed from

**Comment by midget3111** [comment] 2022-03-13 12:16
Could also be an issue with your window manager. What are you using?

**Comment by thelooter** [comment] 2022-03-13 15:38
I'm using KDE 5.24.2

**Comment by trigg** [comment] 2022-03-23 09:09
Can't reproduce this, always appears on top for me

**Comment by midget3111** [comment] 2022-03-23 21:43
Also appears on top for me. I'll close for now and reopen if it's still an issue @thelooter

**Closed by midget3111** 2022-03-23 21:43 UTC
Labels: bug, Cannot reproduce
