### ISSUE TITLE
Does Not Opens

### ISSUE THREAD

**Issue by pofdzm** [trigg/Discover#153] opened 2021-06-23 18:09 UTC
pofdzm@pofdzm:~$ discover-overlay 
Gtk-Message: 21:07:21.096: Failed to load module "pantheon-filechooser-module"
INFO:root:Loading saved channel 854063003745779806
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Loading saved channel 854063003745779806
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Autostart info : desktop /home/pofdzm/.local/share/applications/discover_overlay.desktop auto None

(discover-overlay:16961): Gdk-CRITICAL **: 21:07:21.778: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
INFO:root:ID is 473161853741039636
INFO:root:Logged in as pofdzm.tar.gz
INFO:root:Changing text room: 854063003745779806
Traceback (most recent call last):
  File "/home/pofdzm/.local/lib/python3.6/site-packages/discover_overlay/discord_connector.py", line 590, in do_read
    self.on_message(msg)
  File "/home/pofdzm/.local/lib/python3.6/site-packages/discover_overlay/discord_connector.py", line 374, in on_message
    self.add_text(message)
  File "/home/pofdzm/.local/lib/python3.6/site-packages/discover_overlay/discord_connector.py", line 149, in add_text
    message["timestamp"], "%Y-%m-%dT%H:%M:%S.%f%z")
  File "/usr/lib/python3.6/_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2021-06-23T13:05:22.630Z' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'

It just does not opens.

That is the terminal output. There is still the tray icon, if i press settings this happens in the output:

Traceback (most recent call last):
  File "/home/pofdzm/.local/lib/python3.6/site-packages/discover_overlay/discover_overlay.py", line 137, in show_settings
    self.settings.present_settings()
  File "/home/pofdzm/.local/lib/python3.6/site-packages/discover_overlay/settings_window.py", line 70, in present_settings
    self.text_settings.present_settings()
  File "/home/pofdzm/.local/lib/python3.6/site-packages/discover_overlay/text_settings.py", line 158, in present_settings
    self.connector.request_text_rooms_for_guild(self.guild)
  File "/home/pofdzm/.local/lib/python3.6/site-packages/discover_overlay/discord_connector.py", line 618, in request_text_rooms_for_guild
    None] * len(self.guilds[guild_id]["channels"])
KeyError: 'channels'

How can I fix this?

**Comment by pofdzm** [comment] 2021-06-23 18:13
It just happened after I restarted my pc. It was working fine before. Also sending an interrupt signal with Ctrl+C doesn't works either.

**Comment by trigg** [comment] 2021-06-27 18:31
Duplicate of #58

**Closed by trigg** 2021-06-27 18:31 UTC
