### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by bubblefish-dev** [trigg/Discover#118] opened 2020-11-22 16:50 UTC
I installed discover-overlay successfully without any error. I've Kubuntu 20
It is an error:
```log
Traceback (most recent call last):
  File "/home/theforce/.local/bin/discover-overlay", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/theforce/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 166, in entrypoint
    Discover(rpc_file, line)
  File "/home/theforce/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 40, in __init__
    self.create_gui()
  File "/home/theforce/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 81, in create_gui
    self.voice_overlay = VoiceOverlayWindow(self)
  File "/home/theforce/.local/lib/python3.8/site-packages/discover_overlay/voice_overlay.py", line 24, in __init__
    OverlayWindow.__init__(self)
  File "/home/theforce/.local/lib/python3.8/site-packages/discover_overlay/overlay.py", line 77, in __init__
    self.set_untouchable()
  File "/home/theforce/.local/lib/python3.8/site-packages/discover_overlay/overlay.py", line 141, in set_untouchable
    reg = Gdk.cairo_region_create_from_surface(surface)
KeyError: 'could not find foreign type Surface'
```

> theforce@fugapc:~$ neofetch 
OS: Ubuntu 20.04.1 LTS x86_64 
Kernel: 5.4.0-47-generic 
Shell: bash 5.0.17 
Resolution: 1920x1080, 1920x1080 
DE: Plasma 
WM: KWin 
CPU: Intel i3-9100F (4) @ 3.600GHz 
GPU: NVIDIA GeForce GTX 1060 6GB 
Memory: 4303MiB / 32061MiB

**Comment by stefangehn** [comment] 2020-11-25 20:12
This seems to be a duplicate of #116 (which has a rather unclear title).

I had the same issue on Ubuntu 20.04 and found out that installing `python3-gi-cairo` in addition to `python3-gi`  fixes it.
It looks like the GObject introspection for cairo is in a dedicated package.

**Comment by trigg** [comment] 2020-12-04 17:50
Closing with the fix above. Thank you!

**Closed by trigg** 2020-12-04 17:50 UTC
