### ISSUE TITLE
Overlay only works on Steam Deck Beta branch

### ISSUE THREAD

**Issue by Johnnyhoboy** [trigg/Discover#281] opened 2022-10-08 00:14 UTC
**Steps to Reproduce**
1. On Steam Deck, switch to stable branch
2. Open Discord Overlay
3. Open Discord, join channel
4. The overlay does not pop up

**Expected behavior**
The Discord Overlay pops up

**Problematic behavior**
The Discord Overlay doesn't pop up

**Desktop (please complete the following information):**
 - OS: Latest SteamOS Stable

**Installation Method**
 - The usual installation method from the [website](https://trigg.github.io/Discover/deckaddnonsteamgame)
 - Found initially from this [video](https://youtu.be/9-Eu4o3AzMc)

**Additional context**
I could have sworn I read somewhere months ago that I had to be on beta branch to work. I was helping a friend get Discord overlay on her end to work but it just wouldn't on stable branch. When I switched it to beta branch, it instantly worked.

**Comment by trigg** [comment] 2022-10-08 12:57
Hello!

Have just set my deck back to Stable SteamOS & Stable Steam, and am unable to reproduce this. 

We did have an issue with a mangohud version which didn't give up overlay slot which was later fixed by gamescope, but I've not seen it since then. Worth double-checking for more updates, including an update via flatpak for our overlay

**Comment by midget3111** [comment] 2022-10-09 08:59
I've also just changed over to stable. Also not encountering this. How bizzare!

**Comment by Johnnyhoboy** [comment] 2022-10-09 15:22
Also worth noting I was helping her setup a brand new Steam Deck. I've always had mines on beta branch, but she only kept hers on stable.

**Comment by trigg** [comment] 2022-10-10 08:14
If you're able to get a terminal open on each device and run `pacman -Q gamescope` and post the version numbers here it might help a bit. Essentially this was fixed by the `3.11.31-beta7` version update of gamescope last time.

**Comment by Johnnyhoboy** [comment] 2022-10-12 17:12
On my Steam Deck at least, I see my version is:
gamescope 3.11.47.minimal.jupiter.3.3.2-1

I can ask my friend to run the command on her end, at this point we're just both sticking to beta branch anyways

**Comment by Johnnyhoboy** [comment] 2022-10-13 01:05
My friend switched back to Stable and it now works again for some reason. We didn't change anything from last time. Odd, perhaps a bug with the first time set up and you can't replicate it again after switching to beta and back?

**Closed** 2023-01-06 17:11 UTC
Labels: bug
