### ISSUE TITLE
Names with arabic symbols are suddenly displayed on the right of the screen instead of on the left

### ISSUE THREAD

**Issue by water-carrier3** [trigg/Discover#352] opened 2024-10-29 20:07 UTC
### **Steps to Reproduce**
1. Open discover overlay and discord
2. Change name to 'محمد'
3. Join vc

**Comment by trigg** [comment] 2024-12-16 18:49
Thanks for the report! I'm looking into this now

**Comment by trigg** [comment] 2024-12-16 19:22
I believe I have found the cause here. Closing

**Closed by trigg** 2024-12-16 19:22 UTC
Labels: bug
