### ISSUE TITLE
Allways show last spoken

### ISSUE THREAD

**Issue by darktweek** [trigg/Discover#119] opened 2020-11-29 22:17 UTC
Hi !
Good work for this feature, but if you enable the "Display Speaker Only" if no one speak, you have the avatar of the last spoken in red.
Also if you disconnect voice channel this icon stay on.

**Comment by midget3111** [comment] 2022-03-23 21:23
Is this still an issue?

**Comment by darktweek** [comment] 2022-03-23 21:27
Don't know, I have switch to windows month a go

**Comment by midget3111** [comment] 2022-03-23 21:28
As I can't reproduce this, I'm going to close the issue for now.

**Closed by midget3111** 2022-03-23 21:28 UTC
Labels: enhancement, Cannot reproduce
