### ISSUE TITLE
Doesn't work well with compositors.

### ISSUE THREAD

**Issue by tpurde** [trigg/Discover#80] opened 2020-10-09 21:25 UTC
Apparently, Discover takes over the whole screen. Due to this, compositors that disable themselves (like Kwin or Picom) or compositors with blur (like picom-git) won't work well at all with Discover while games are open, which is the whole point of it.

**Comment by trigg** [comment] 2020-10-10 14:30
Duplicate of #74 

It should revert to non-composite mode if the compositor disables when going fullscreen.

**Comment by tpurde** [comment] 2020-10-10 17:02
Well, it doesn't seem like it reverts and the game goes fully black.

**Comment by trigg** [comment] 2020-10-10 17:04
That's absolutely not intended behavior. Do you get any console output when it happens? Possibly try running overlay from a TTY so you can ctrl-alt-f2 to get back to it

**Comment by tpurde** [comment] 2020-10-10 17:06
I was running from a terminal so I can see the logs, as Picom only disables compositing on a single workspace. There isn't any info except server data and me joining a voice channel.

**Comment by trigg** [comment] 2020-10-11 13:47
So it looks like picom isn't disabling compositor in a way that can be detected. I'll probably need to give the user the option to opt-out of auto detection and just to choose XShape or composite from settings.

**Comment by tpurde** [comment] 2020-10-11 17:47
User option to opt in or out would be useful indeed.

**Comment by trigg** [comment] 2020-10-12 00:25
Last push has a tickbox to force use of XShape. Let me know how it goes

**Comment by tpurde** [comment] 2020-10-12 11:19
Anchoring to edge still makes the game go fully black, but making it float works, albeit with a gross black box.

**Comment by trigg** [comment] 2020-10-12 11:40
I'm unable to reproduce this with XFWM & Picom-git, with or without xshape forced. What picom flags are you settings? What window manager is being used?

**Comment by tpurde** [comment] 2020-10-12 12:00
I'm using bspwm right now. Picom by default does not disable itself on fullscreen applications, this line in picom.conf does it for me:
`unredir-if-possible = true;`

Here is how a game (Half-Life 2: Episode 1 in this case) looks with anchor to edge (Names are disabled): 
![image](https://user-images.githubusercontent.com/62025836/95744238-b325df80-0c9b-11eb-8a3c-df7d0746e0df.png)

**Comment by trigg** [comment] 2020-10-12 12:21
So I've installed bspwm & picom-git and tested.

That option appears to only allow one window to render at all. When I use it all windows other than active are not rendered. I would strongly suggest this is a bug in picom (and picom-git).

I did the same with xfwm4 and that flag only renders a single window again, even if nothing is fullscreen.

**Comment by tpurde** [comment] 2020-10-12 13:39
> So I've installed bspwm & picom-git and tested.
> 
> That option appears to only allow one window to render at all. When I use it all windows other than active are not rendered. I would strongly suggest this is a bug in picom (and picom-git).
> 
> I did the same with xfwm4 and that flag only renders a single window again, even if nothing is fullscreen.

Well that is interesting, if I make the game float, I can open another window like a terminal window and both of them will continue to work. I wonder if there is another way to disable compositing when fullscreen applications are present?

**Comment by trigg** [comment] 2020-10-12 13:46
Looking further. It seems that feature isn't working on intel igpu, so I'm assuming my hardware. When I'm able to get to it my main computer uses picom & has amd gpu so I will test again.

**Comment by tpurde** [comment] 2020-10-12 17:10
I was testing on Nvidia with proprietary drivers.

**Comment by trigg** [comment] 2020-10-12 17:28
With AMD the overlay is the only window drawn with openbox/picom and the setting '--unredir-if-possible' 

Xfwm4 has a similar option which does not cause this issue, further cementing my belief that the issue lies with picom

**Comment by tpurde** [comment] 2020-10-12 18:08
Just to note, forcing XShape makes no difference on me, at all.

**Comment by tpurde** [comment] 2020-10-12 18:13
> With AMD the overlay is the only window drawn with openbox/picom and the setting '--unredir-if-possible'
> 
> Xfwm4 has a similar option which does not cause this issue, further cementing my belief that the issue lies with picom

I don't really know any other X compositors that have the option to disable themselves on a fullscreen application, sadly I may not test this. KDE's compositor does have that feature though.

**Comment by trigg** [comment] 2020-10-12 18:15
xfwm4 has a unredirect on fullscreen which, as expected, doesn't trigger because an overlay is being drawn over full screen.

**Comment by tpurde** [comment] 2020-10-12 18:16
> xfwm4 has a unredirect on fullscreen which, as expected, doesn't trigger because an overlay is being drawn over full screen.

Ah alright, seems like a Picom issue then. If it's a Picom issue, will you have to report it to them?

**Closed** 2020-10-17 16:01 UTC
Labels: bug, duplicate, wontfix
