### ISSUE TITLE
[QA] One .desktop file does not pass validation

### ISSUE THREAD

**Issue by NicolaSmaniotto** [trigg/Discover#270] opened 2022-07-23 10:13 UTC
**Steps to Reproduce**
1. Run `desktop-file-validate discover_overlay_configure.desktop`

**Expected behavior**
No output should be printed

**Problematic behavior**
Errors are printed:
```
discover_overlay_configure.desktop: error: action "close" is defined, but there is no matching "Desktop Action close" group
discover_overlay_configure.desktop: error: action "configure" is defined, but there is no matching "Desktop Action configure" group
```

**Desktop:**
 - OS: Linux

**Installation Method**
 - Not relevant

**Additional Context**
- [desktop-file-utils](https://www.freedesktop.org/wiki/Software/desktop-file-utils/) version: 0.26

**Comment by trigg** [comment] 2022-07-23 16:51
What's your installation method?

Source git hasn't complained
```
[triggerhapp@raven Discover]$ desktop-file-validate discover_overlay.desktop 
[triggerhapp@raven Discover]$ 
```

**Comment by trigg** [comment] 2022-07-23 16:55
Ah the problem is my reading comprehension, my apologies I see it now

**Comment by trigg** [comment] 2022-07-23 16:58
Fixed in latest git, thank you!

**Closed by trigg** 2022-07-23 16:58 UTC

**Comment by NicolaSmaniotto** [comment] 2022-07-29 08:48
Sorry I didn't reply, I was away for the week. I'm glad you still understood what I meant

**Comment by trigg** [comment] 2022-07-29 09:13
You were absolutely clear enough, I just had a moment there. Thanks again and hope you had a good week away
