### ISSUE TITLE
Add option to use nicknames instead of usernames

### ISSUE THREAD

**Issue by Joshix-1** [trigg/Discover#91] opened 2020-10-19 14:52 UTC

**Comment by trigg** [comment] 2020-10-19 14:57
Care to elaborate?

**Comment by midget3111** [comment] 2020-10-19 14:57
Fairly sure nicknames are the default in the later versions?

**Comment by trigg** [comment] 2020-10-19 15:29
Duplicate of #83

**Comment by Joshix-1** [comment] 2020-10-19 15:52
The I'm stupid.
![image](https://user-images.githubusercontent.com/57299889/96475053-da4c5600-1233-11eb-9701-e8f862c3ccc5.png)

**Comment by trigg** [comment] 2020-10-19 17:40
Are you on stable or latest?

**Comment by Joshix-1** [comment] 2020-10-19 17:59
I'm on stable. The chat uses nicknames.

**Comment by trigg** [comment] 2020-10-19 18:03
Fixed in latest, doing a push towards new stable 0.3.0 soon

**Closed by trigg** 2020-10-19 18:03 UTC
