### ISSUE TITLE
doesn't work on vesktop

### ISSUE THREAD

**Issue by fe2-Nyxar** [trigg/Discover#350] opened 2024-10-04 18:39 UTC
it's not a bug, I just installed Vesktop and tried to use discover-overlay, and it doesn't work, I'm just asking if we can get a compatible version with Vesktop.

### **Desktop (please complete the following information):**
 - Operating System / Distrobution: Nixos
 - Desktop Environment: Plasma 6

### **Installation Method**
 - nixpkgs

**Comment by trigg** [comment] 2024-12-16 19:26
Unfortunately a duplicate of #312 . Closing in favour of that one

**Closed by trigg** 2024-12-16 19:26 UTC
Labels: bug
